import { ArrowLeft, Box, Camera, Check, ChevronRight, Clipboard, Construction, ImagePlus, Layers3, Play, Search, Sparkles, Upload, UserRound } from 'lucide-react'
import { useRef, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { useToast } from '@/components/ToastProvider'
import { useSceneStore } from '@/store'

function PageHeader({ title }: { title: string }) { const navigate = useNavigate(); return <header className='flow-header'><button type='button' onClick={() => navigate(-1)} aria-label='返回'><ArrowLeft /></button><strong>{title}</strong><Link to='/'>Feed</Link></header> }
const scenes = [{ id: 'calm', name: '松弛独处', copy: '降低视觉噪声，保留阅读和休息的连续区域。' }, { id: 'gather', name: '朋友来访', copy: '围合座位关系，释放共享活动中心。' }, { id: 'focus', name: '高效专注', copy: '将任务照明、收纳和工作台组织在一起。' }]

export function HomePage() {
  return <div className='surface-page'><header className='surface-hero'><div><span>MY HOME · ROOM6</span><h1>我的家</h1><p>当前方案中的家具、户型和最近保存状态。</p></div><Link className='primary-link' to='/space?sceneId=room6'><Box />打开 3D 空间</Link></header><section className='metric-grid'><article><strong>room6</strong><span>当前户型</span></article><article><strong>6.0 × 4.2m</strong><span>室内范围</span></article><article><strong>实时快照</strong><span>刷新后恢复</span></article></section><section className='content-band'><h2>继续设计</h2><Link className='wide-row' to='/space?sceneId=room6'><Layers3 /><div><strong>客厅方案</strong><p>编辑全部家具、墙体与运行版白模</p></div><ChevronRight /></Link></section></div>
}

export function DiscoverPage() { return <div className='surface-page'><header className='surface-hero'><div><span>LAYOUT DIRECTIONS</span><h1>场景方向</h1><p>从生活方式出发组织空间，而不是只改变单件家具。</p></div></header><section className='scene-grid'>{scenes.map((s, i) => <Link to={`/scene/${s.id}`} className='scene-card' key={s.id}><span>0{i + 1}</span><h2>{s.name}</h2><p>{s.copy}</p><ChevronRight /></Link>)}</section></div> }

export function MePage() {
  const toast = useToast(); const active = useSceneStore((s) => s.activeSceneId); const setActive = useSceneStore((s) => s.setActiveSceneId); const input = useRef<HTMLInputElement>(null)
  return <div className='surface-page'><header className='surface-hero'><div><span>PROFILE & FLOORPLAN</span><h1>我的</h1><p>管理演示户型和建模入口。</p></div><UserRound className='hero-icon' /></header><section className='content-band'><h2>我的户型</h2><div className='room-choice'><button className={active === 'room6' ? 'is-active' : ''} onClick={() => { setActive('room6'); toast.show('已使用 room6') }} type='button'><Check />room6<small>6.0 × 4.2m · 可用</small></button><button disabled type='button'><Construction />room1<small>后续接入</small></button><button disabled type='button'><Construction />room8<small>后续接入</small></button></div></section><section className='content-band'><h2>全屋扫描</h2><input ref={input} hidden type='file' accept='image/*,video/*' onChange={(event) => { if (!event.target.files?.length) return; setActive('room6'); toast.show('扫描素材已接收，演示模式已匹配 room6'); event.target.value = '' }} /><button className='wide-row' type='button' onClick={() => input.current?.click()}><Upload /><div><strong>上传全屋扫描素材</strong><p>演示模式：上传后直接使用 room6，不调用实时重建</p></div><ChevronRight /></button></section></div>
}

export function ProductPage() { const { id } = useParams(); return <div className='flow-page'><PageHeader title='单品详情' /><main className='detail-layout'><div className='detail-visual'><Box /></div><div><span className='eyebrow'>PRODUCT · {id}</span><h1>识别家具</h1><p>这里承接搜同款、材质与尺寸信息。演示主链使用预处理 GLB，不触发实时生成。</p><Link className='primary-link' to='/space?sceneId=room6'>放入 room6</Link></div></main></div> }
export function ScenePage() { const { id } = useParams(); const scene = scenes.find((s) => s.id === id) ?? scenes[0]; return <div className='flow-page'><PageHeader title='场景详情' /><main className='detail-layout'><div className='detail-visual'><Sparkles /></div><div><span className='eyebrow'>SCENE DIRECTION</span><h1>{scene.name}</h1><p>{scene.copy}</p><Link className='primary-link' to={`/space?sceneId=room6&direction=${scene.id}`}>按此方向试改</Link></div></main></div> }

export function RecognizePage() { const input = useRef<HTMLInputElement>(null); const navigate = useNavigate(); const [selected, setSelected] = useState(false); return <div className='flow-page'><PageHeader title='识别家具' /><main className='center-flow'><Camera /><h1>补充一件家具</h1><p>上传图片或从 Feed 暂停识别。当前上传识别为页面级 Mock。</p><input ref={input} hidden type='file' accept='image/*' onChange={() => setSelected(true)} /><button type='button' className='primary-button' onClick={() => input.current?.click()}><ImagePlus />{selected ? '重新选择图片' : '选择家具图片'}</button>{selected && <button type='button' className='secondary-button' onClick={() => navigate('/space?sceneId=room6')}><Check />使用识别结果</button>}</main></div> }
export function SuggestPage() { return <div className='flow-page'><PageHeader title='布局建议' /><main className='center-flow'><Sparkles /><h1>空间建议已整理</h1><p>主通道、尺寸适配和材质语义建议会在 3D 编辑器内直接展示并应用。</p><Link className='primary-link' to='/space?sceneId=room6'>回到空间</Link></main></div> }
export function RecommendPage() { return <div className='flow-page'><PageHeader title='搜同款' /><main className='center-flow'><Search /><h1>相似家具</h1><p>商品检索接口已经保留。这里作为主链之外的扩展入口。</p><div className='recommend-grid'>{['同材质单椅', '相近尺寸边几', '同色系落地灯'].map((name) => <article key={name}><Box /><strong>{name}</strong><button type='button'>查看详情</button></article>)}</div></main></div> }
export function CompletePage() { return <div className='flow-page'><PageHeader title='方案完成' /><main className='center-flow'><Check /><h1>方案已保存</h1><p>家具坐标、尺寸、语义和墙体已写入 room6 SceneSnapshot。</p><Link className='primary-link' to='/'>继续看 Feed</Link></main></div> }
export function DashboardPage() { const toast = useToast(); return <div className='flow-page'><PageHeader title='开发看板' /><main className='dashboard'><h1>接口与演示入口</h1><div className='endpoint-list'>{['GET /api/room/snapshots/room6', 'PUT /api/room/snapshots/room6', 'PUT /api/room/snapshots/room6/whitebox', 'POST /api/room/room-layout', 'POST /api/feed/detect'].map((path) => <button type='button' key={path} onClick={() => navigator.clipboard?.writeText(path).then(() => toast.show('已复制接口')).catch(() => toast.show(path))}><Clipboard />{path}</button>)}</div><Link className='primary-link' to='/'><Play />开始演示</Link></main></div> }
